language: node_js
node_js:
  - "8"
install:
  - npm install
script:
  - npm test
cache:
  directories:
    - "node_modules"
deploy:
  before_deploy:
    - node -p -e "'v' + require('./package').version" | xargs git diff --exit-code --stat
  on:
    tags: true
