language: node_js
node_js:
  - "8"
install:
  - npm install
script:
  - npm test
cache:
  directories:
    - "node_modules"
deploy:
  before_deploy:
    - git diff --exit-code --stat $(node -p -e "require('./package').version")
  on:
    tags: true
